<a href="https://colab.research.google.com/github/Shradha1304/myrepo/blob/main/2_IMDB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [41]:
from tensorflow.keras.datasets import imdb

In [35]:
df=imdb.load_data(num_words=10000)

In [ ]:
print(df)

In [2]:
(train_data, train_label), (test_data, test_label) = imdb.load_data(num_words = 10000)

17464789/17464789 [==============================] - 0s 0us/step


In [ ]:
print(train_data)# ha data bagh vegla vegla ahee...

In [39]:
print(train_label)

[1 0 0 ... 0 1 0]


numpy basic library ahe tula asa mathematical operation perform karayla help kartaaa`,dimension manjhe apan vachla naa max index 10000 mahatvach ewords

In [42]:
import numpy as np

def vectorize_sequences(sequences, dimensions = 10000):
  results = np.zeros((len(sequences), dimensions))
  for i,sequences in enumerate(sequences):
    results[i, sequences] = 1
  return results
#ka
# Vectorize testing Data
X_test = vectorize_sequences(test_data)
x_train = vectorize_sequences(train_data)


In [43]:
print(x_train)#but ithe bagh apan encode kela ani te positive negavtive zhale

[[0. 1. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 ...
 [0. 1. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]]


In [44]:
y_train = np.asarray(train_label).astype('float32')
y_test = np.asarray(test_label).astype('float32')


In [46]:
print(y_train)

[1. 0. 0. ... 0. 1. 0.]


In [45]:
print(y_test)

[0. 1. 1. ... 0. 0. 0.]


In [47]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [48]:
model = Sequential()
model.add(Dense(16, input_shape=(10000, ), activation = "relu"))
model.add(Dense(16, activation = "relu"))
model.add(Dense(1, activation = "sigmoid"))

In [49]:
model.compile(optimizer='adam', loss = 'mse', metrics = ['accuracy'])

In [50]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_6 (Dense)             (None, 16)                160016    
                                                                 
 dense_7 (Dense)             (None, 16)                272       
                                                                 
 dense_8 (Dense)             (None, 1)                 17        
                                                                 
Total params: 160305 (626.19 KB)
Trainable params: 160305 (626.19 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [51]:
history = model.fit(x_train, y_train, validation_split = 0.3, epochs = 20, verbose = 1, batch_size = 512)

Epoch 1/20
35/35 [==============================] - 3s 69ms/step - loss: 0.1950 - accuracy: 0.7495 - val_loss: 0.1287 - val_accuracy: 0.8627
Epoch 2/20
35/35 [==============================] - 1s 37ms/step - loss: 0.0934 - accuracy: 0.9009 - val_loss: 0.0895 - val_accuracy: 0.8887
Epoch 3/20
35/35 [==============================] - 1s 37ms/step - loss: 0.0606 - accuracy: 0.9342 - val_loss: 0.0824 - val_accuracy: 0.8917
Epoch 4/20
35/35 [==============================] - 1s 34ms/step - loss: 0.0459 - accuracy: 0.9526 - val_loss: 0.0817 - val_accuracy: 0.8901
Epoch 5/20
35/35 [==============================] - 1s 34ms/step - loss: 0.0352 - accuracy: 0.9656 - val_loss: 0.0834 - val_accuracy: 0.8863
Epoch 6/20
35/35 [==============================] - 2s 59ms/step - loss: 0.0271 - accuracy: 0.9764 - val_loss: 0.0848 - val_accuracy: 0.8856
Epoch 7/20
35/35 [==============================] - 2s 49ms/step - loss: 0.0209 - accuracy: 0.9831 - val_loss: 0.0880 - val_accuracy: 0.8817
Epoch 8/20
35

In [52]:
model.evaluate(X_test,y_test)

782/782 [==============================] - 4s 5ms/step - loss: 0.1155 - accuracy: 0.8562


[0.11553272604942322, 0.8561599850654602]

In [53]:
y_pred=model.predict(X_test)

782/782 [==============================] - 3s 3ms/step


In [58]:
print(y_pred[1],y_test[1])

[1.] 1.0
